## This is use to setup the argoCD in a declarative mode
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Nginx-app
  namespace: argo
spec:
  project: default
  source:
    repoURL:https://github.com/Rajan1812/argoCD.git
    targetRevision: HEAD
    path: nginx-app
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace = true