#This will start a serive suing the deployment created
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000